# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - code/funcsrt

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      sudo apt install zip
      zip -r deploy.zip . -i SampleFunctionsBundleStateless/ host.json
    workingDirectory: '$(System.DefaultWorkingDirectory)/code/funcsrt'
    
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'FTA fmiguel - Azure CXP Internal(98bc5d13-2aa1-45cb-bf49-45aa47e220bf)'
    appType: 'workflowapp'
    appName: 'app-demo-logicapp-0127-dev-001'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
