# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - code/dotnet

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    workingDirectory: 'code/dotnet'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*/**/code.csproj'
    feedsToUse: 'select'
    workingDirectory: code/dotnet
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '*/**/code.csproj'
    workingDirectory: 'code/dotnet'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'FTA fmiguel - Azure CXP Internal(98bc5d13-2aa1-45cb-bf49-45aa47e220bf)'
    appType: 'workflowapp'
    appName: 'app-demo-logicapp-0127-dev-001'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
